#!/usr/bin/node

const http = require('http');
      fs = require('fs');

http.createServer((req,res)=>{
  var fileName = __dirname + req.url;
  console.log(fileName);
  res.end(fs.readFileSync(fileName))
    }).listen(8080)//未写完
